### ISSUE TITLE
Stream Live

### ISSUE THREAD

**Issue by cyberience** [Adeithe/go-twitch#10]
This is not really a bug issue, more of question.
I am struggling to identify if a Stream starts or stops, the issue I come up on is if the channel stops streaming, then they return later, the application is still connected to the previous stream chat, but not the new stream chat, only fix is to disconnect and reconnect, to do this Programatically, I would need to detect if the stream is still live, and put the service to sleep till it becomes live again, is there a method within the library that would enable this?

**Comment by Adeithe** [comment]
You can use the `helix` API to request the channels stream periodically (every 5 minutes for example) to detect if a stream has gone online/offline and join chat once the API returns that there is an active stream.

If you are using IRC, the channels chatroom does not change with each stream and you can remain in chat while the stream is offline.
