### ISSUE TITLE
[Question] why you answer a PING with another PING?

### ISSUE THREAD

**Issue by sainoba** [Adeithe/go-twitch#15]
First of all sorry for the noise, I didn't find another place to ask this.

Reading through your code I noticed that when you receive a PING from twitch you answer with another PING instead of answering with a PONG, as the [documentation suggests](https://dev.twitch.tv/docs/irc/#keepalive-messages).

Is this intentional? and if so, why?

PS. thanks for working on this library, its the most complete twitch library in Go.

https://github.com/Adeithe/go-twitch/blob/eee71bbf962d35422efb687cd4310da06a344485/irc/conn.go#L351-L352

https://github.com/Adeithe/go-twitch/blob/eee71bbf962d35422efb687cd4310da06a344485/irc/conn.go#L168-L178

**Comment by Adeithe** [comment]
A `PING/PONG` is only required to prevent the connection from being deemed dead by Twitch and closed from their end. You do not need to send any `PONG` messages as long as a `PING/PONG` is sent from either end. 

Sending a `PING` instead allows the client to easily track the latency to the server, which is then made available by the library if needed.
