### ISSUE TITLE
[Suggestion] Allow updating the IRC token so Conn uses a valid token at Reconnect

### ISSUE THREAD

**Issue by sainoba** [Adeithe/go-twitch#16]
Auth tokens can expires as early as 4 hours after their creation. So reconnecting the IRC client after a few hours is doom to fail unless you can programmatically update the token in Conn to a recently refreshed token.

https://github.com/Adeithe/go-twitch/blob/e09217ee922080aa2837c172e8a804c2ed5b6978/irc/conn.go#L16-L20

So it may be a good idea to either:
- Allow `SetLogin` to set the credentials even if there's an existing connection, knowing that this new credentials would only be used until a reconnect happens
- Or add a new function like `SetLoginForReconnect(username, token string)` to make it more explicit 🤷‍♀️

Btw congrats on the new Release 🎉

**Comment by Adeithe** [comment]
Authorization tokens generated via the [implicit grant flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#implicit-grant-flow) generally don't expire and are best suited when running a bot. You can put together the link for this yourself or log in using [TwitchApps TMI](https://twitchapps.com/tmi/) and grab the token from there if you'd rather skip building the link.

**Comment by Satont** [comment]
They are, and in real production application you will never use `implicit` flow, because you want your tokens up to date. So, that issue is correct, and IMO it should be done somehow.

I'd like to suggest introduce some function with callback, `GetOauthToken`, for example, which will be called for getting token on initial connection, and on reconnections.

Otherwise when reconnection happening and token is expired - bot crashing,

**Comment by Satont** [comment]
Also for example https://github.com/gempir/go-twitch-irc just throwing error on `client.Connect()` function, and you can do infinity loop with getting token inside of.

I'm not like that way and leaning to callback way.

**Comment by Satont** [comment]
@sainoba do you somehow fixed this?

I mean i need example for proper reconnect with new token, because my production application already lost chat connection because of token expiration.
