### ISSUE TITLE
Error while fetching Videos

### ISSUE THREAD

**Issue by Niki2k1** [Adeithe/go-twitch#18]
I am not able to fetch the recent videos of a Streamer. I get the following error:

`json: cannot unmarshal string into Go struct field Video.data.duration of type time.Duration`

**My Code**
```
videoCall := client.Videos.List().UserID("50985620").Type("archive")

videos, err := videoCall.Do(context.Background(), api.WithBearerToken(bearer.AccessToken))
	
if err != nil {
	panic(err)
}

fmt.Println(videos.Data[0].Title)
```

**What I tried**
I modified twitch_videos.go to print the response of the twitch response.
I took out every duration and tried to parse it: https://go.dev/play/p/iY-z3kKFArE

That ended up working so I think its not the data thats coming from Twitch.

But as I am not that confident with go yet I have no Idea how to continue

**Comment by Adeithe** [comment]
Fixed via #19
