### ISSUE TITLE
[feature request] Add reply to writer

### ISSUE THREAD

**Issue by Satont** [Adeithe/go-twitch#20]

**Comment by Adeithe** [comment]
Closing as no information provided. Assuming you are referring to Twitchs native reply feature, you can use the `SendRaw` function to add the required tag yourself. https://dev.twitch.tv/docs/irc/send-receive-messages/#replying-to-a-chat-message

**Comment by Satont** [comment]
In my opinion it will not be superfluous, i can do PR if you wont do it yourself.
