### ISSUE TITLE
[feature request] Add parsing of emotes in chat message

### ISSUE THREAD

**Issue by Satont** [Adeithe/go-twitch#21]
https://dev.twitch.tv/docs/irc/tags/#privmsg-tags has emotes, but `reader.OnShardMessage` not.

**Comment by Adeithe** [comment]
Closing. This data is available via the `IRCMessage.Tags` map on the ChatMessage object provided in the `OnShardMessage` event, if this field is not included in the tags map then it was not provided on Twitchs end.

**Comment by Satont** [comment]
So `tags` contains everything from `PRIVMSG`, make sense now. 

Thanks.
