### ISSUE TITLE
Helix Request function

### ISSUE THREAD

**Issue by codedninja** [Adeithe/go-twitch#6]
After looking over the docs, I haven't been able to find an export for making custom Helix requests. Is there one I am missing or should I create it and make a pull request.

**Comment by Adeithe** [comment]
You can make a custom Helix request by using the Request function exported in the Helix API client. The client will add the Client-ID and OAuth headers for you. 

Code is untested but this should work after handling the request response appropriately. Note that the base URL is omitted in the request path.
```go
package main 

import (
	"net/http"
	"github.com/Adeithe/go-twitch"
)

func main() {
	api := twitch.API("myclientid")
	bearer := api.NewBearer("myoauthtoken")
	helix := bearer.Helix()

	res, err := helix.Request(http.MethodGet, "bits/cheermotes?broadcaster_id=71092938", nil)
	if err != nil {
		panic(err)
	}
	// Code to handle the request response...
}
```
[Link to documentation](https://pkg.go.dev/github.com/Adeithe/go-twitch@v0.0.0-20210130035603-45f857dc288a/api/helix#Client.Request)
